/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //docsSidebar: [{ type: 'autogenerated', dirName: '.' }]

  // But you can create a sidebar manually

  docsSidebar: [
    {
      type: 'doc',
      id: 'introduction',
      label: 'Introduction'
    },
    {
      type: 'doc',
      id: 'authentication',
      label: 'Authentication'
    },
    {
      type: 'doc',
      id: 'build-basics',
      label: 'Build Basics'
    },
    {
      type: 'doc',
      id: 'testing',
      label: 'Testing'
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: "App payments",
          collapsed: false,
          items: [
            'guides/app-payments/how-it-works',
            'guides/app-payments/build-on-mobile',
          ]
        }
      ]
    },
    {
      type: 'doc',
      id: 'payment-points',
      label: 'Payment Points'
    },
    {
      type: 'category',
      label: 'Payments and Refunds',
      collapsed: false,
      items: [
        'payments-refunds/overview',
        'payments-refunds/create-payments',
        'payments-refunds/refund-payments',
        'payments-refunds/error-codes',
      ]
    },
    {
      type: 'doc',
      id: 'webhooks',
      label: 'Webhooks'
    },
    {
      type: 'doc',
      id: 'release-notes',
      label: 'Release Notes'
    }
  ],
  reportingSidebar: [
    {
      type: 'doc',
      id: 'reporting/overview',
      label: 'MobilePay Reporting'
    },
    {
      type: 'doc',
      id: 'reporting/getting-started',
      label: 'Getting started'
    },  
    {
      type: 'category',
      label: 'Authentication',
      collapsed: true,
      link: {
        type: 'generated-index',
        description: 'Learn about authentication for Reporting API',
      },
      items: [
        'reporting/authentication/authentication',
        'reporting/authentication/api-key',
        {
          type: 'category',
          label: 'OAuth',
          collapsed: true,
          link: {
            type: 'generated-index',
            description: 'Learn about OAuth authentication for Reporting API',
          },
          items: [
            'reporting/authentication/open-id/open-id',
            'reporting/authentication/open-id/authorize',
            'reporting/authentication/open-id/code',
            'reporting/authentication/open-id/tokens',
            'reporting/authentication/open-id/refresh-tokens',
            
          ],
        },
      ],
    },
    {
      type: 'doc',
      id: 'reporting/payment-points',
      label: 'Retrieve payment points'
    },
    {
      type: 'doc',
      id: 'reporting/transactions',
      label: 'Retrieve transactions'
    },
    {
      type: 'doc',
      id: 'reporting/transfers',
      label: 'Retrieve transfers'
    },
    {
      type: 'doc',
      id: 'reporting/migrate-from-v1v2',
      label: 'Migrate from v1 and v2'
    },
  ],
  onlineSidebar: [
    {
      type: 'doc',
      id: 'online/overview',
      label: 'MobilePay Online'
    },  
    {
      type: 'category',
      label: 'Development Guide',
      collapsed: true,
      link: {
        type: 'generated-index',
        description: 'Learn how to integrate MobilePay Online',
      },
      items: [
        'online/development-guide/getting-started',
        'online/development-guide/test',
        'online/development-guide/verification',
        'online/development-guide/production'
      ],
    },
    {
      type: 'category',
      label: 'Basics',
      collapsed: false,
      link: {
        type: 'generated-index',
      },
      items: [
        'online/basics/merchants',
        'online/basics/payments',
        'online/basics/flow',
        'online/basics/retry-policy',
        'online/basics/callbacks',
        'online/basics/request-fishing',
        'online/basics/error-codes',
        'online/basics/allowed-currencies',
        'online/basics/allowed-card-types'
      ]
    },
    {
      type: 'doc',
      id: 'online/sca',
      label: 'Strong customer authentication'
    },
    {
      type: 'category',
      label: 'Features',
      collapsed: true,
      link: {
        type: 'generated-index',
      },
      items: [
        'online/features/invalidation',
        'online/features/phone-number',
        'online/features/checkout',
        'online/features/embedded-flow'
      ]
    },
    {
      type: 'doc',
      id: 'online/resources',
      label: 'Resources'
    }
  ],
  subscriptionsSidebar: [
    {
      type: 'doc',
      id: 'subscriptions/overview',
      label: 'MobilePay Subscriptions'
    },  
    {
      type: 'category',
      label: 'Development Guide',
      collapsed: false,
      link: {
        type: 'generated-index',
        description: 'Learn how to integrate MobilePay Subscriptions',
      },
      items: [
        'subscriptions/development-guide/getting-started',
        'subscriptions/development-guide/test',
        'subscriptions/development-guide/verification',
        'subscriptions/development-guide/production'
      ],
    },
    {
      type: 'category',
      label: 'Authentication',
      collapsed: false,
      link: {
        type: 'generated-index',
        description: 'Learn about authentication for MobilePay Subscriptions',
      },
      items: [
        'subscriptions/authentication/authentication',
        'subscriptions/authentication/open-id/authorize',
        'subscriptions/authentication/open-id/code',
        'subscriptions/authentication/open-id/tokens',
        'subscriptions/authentication/open-id/refresh-tokens',
            
          ],
    },
    {
      type: 'doc',
      id: 'subscriptions/resources',
      label: 'Resources'
    }
  ],
  posSidebar: [
    {
      type: 'doc',
      id: 'pos/overview',
      label: 'MobilePay PoS',
    },  
    {
      type: 'category',
      label: 'Development Guide',
      collapsed: true,
      link: {
        type: 'generated-index',
        description: 'Learn how to integrate MobilePay Point of Sale',
      },
      items: [
        'pos/development-guide/getting-started',
        'pos/development-guide/test',
        'pos/development-guide/verification',
        'pos/development-guide/production'
      ],
    },
	{
      type: 'doc',
      id: 'pos/authentication',
      label: 'Authentication'
    },
	{
      type: 'doc',
      id: 'pos/detecting-mobilepay',
      label: 'Detecting MobilePay'
    },
    {
      type: 'category',
      label: 'Payment Flows',
      collapsed: false,
      link: {
        type: 'generated-index',
        description: 'Learn about payment flows',
      },
      items: [
        'pos/payment-flows/flows',
        'pos/payment-flows/payment-flow',
        'pos/payment-flows/prepared-payment-flow',
        'pos/payment-flows/payment-flow-error-handling',
        'pos/payment-flows/refunds',
        'pos/payment-flows/cancel-flows',
        'pos/payment-flows/partial-capture'
      ],
    },
	{
      type: 'doc',
      id: 'pos/pos-management',
      label: 'PoS Management'
    },
	{
      type: 'doc',
      id: 'pos/notification-service',
      label: 'Notification Service'
    },
	{
      type: 'doc',
      id: 'pos/best-practices',
      label: 'Best Practices'
    },
	{
      type: 'doc',
      id: 'pos/api-principles',
      label: 'API Principles'
    },
	{
      type: 'doc',
      id: 'pos/self-certification',
      label: 'Self Certification'
    },
	{
      type: 'doc',
      id: 'pos/api-errors',
      label: 'API Errors'
    },
	{
      type: 'doc',
      id: 'pos/input-and-output-formats',
      label: 'Input and Output Formats'
    },
	{
      type: 'doc',
      id: 'pos/create-qr-codes',
      label: 'Create QR Codes'
    },
	{
      type: 'doc',
      id: 'pos/release-notes',
      label: 'Release Notes'
    },
	{
      type: 'doc',
      id: 'pos/glossary',
      label: 'Glossary'
    },
    {
      type: 'doc',
      id: 'pos/resources',
      label: 'Resources'
    }
  ],
  invoiceSidebar: [
    {
      type: 'doc',
      id: 'invoice/overview',
      label: 'MobilePay Invoice'
    },  
    {
      type: 'category',
      label: 'Development Guide',
      collapsed: false,
      link: {
        type: 'generated-index',
        description: 'Learn how to integrate MobilePay Invoice',
      },
      items: [
        'invoice/development-guide/getting-started',
        'invoice/development-guide/test',
        'invoice/development-guide/verification',
        'invoice/development-guide/production'
      ],
    },
    {
      type: 'category',
      label: 'Authentication',
      collapsed: false,
      link: {
        type: 'generated-index',
        description: 'Learn about authentication for MobilePay Invoice',
      },
      items: [
        'invoice/authentication/authentication',
        'invoice/authentication/open-id/authorize',
        'invoice/authentication/open-id/code',
        'invoice/authentication/open-id/tokens',
        'invoice/authentication/open-id/refresh-tokens',
            
          ],
      },
    {
      type: 'doc',
      id: 'invoice/resources',
      label: 'Resources'
    }
  ],
  supportSidebar: [
    {
      type: 'doc',
      id: 'support/support',
      label: 'Support'
    },  
    {
      type: 'doc',
      id: 'support/faq',
      label: 'FAQ'
    }, 
  ]
}
